name: Helios
description: ${description}
authors: [ TehBrian ]
website: https://github.com/SkyboundCity/Helios

version: ${version}
api-version: 26.2
load: STARTUP
main: city.skybound.helios.HeliosPlugin
bootstrapper: city.skybound.helios.HeliosBootstrap

dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: true
