name: Helios
description: ${description}
authors: [ TehBrian ]
website: https://github.com/SkyboundCity/Helios

version: ${version}
main: city.skybound.helios.HeliosPlugin
api-version: 26.2

dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: true
