name: Helios
description: ${description}
authors: [ TehBrian ]
website: https://github.com/SkyboundCity/Helios

version: ${version}
main: city.skybound.helios.Helios
api-version: 26.2

depend: [ LuckPerms ]
load: STARTUP
